### ISSUE TITLE
include flux

### ISSUE THREAD

**Issue by fraserxu** [irvinebroque/isomorphic-hot-loader#1]
Hi @irvinebroque great stack!

Have you ever think about to include flux as well? I'd like to see that.

**Comment by irvinebroque** [comment]
Hey everyone, I just updated this with some very minimal flux stores, dispatcher, and actions.

Lots more to come soon, but I'm curious where people are getting stuck with server-side Flux. Is it dealing with sessions?

**Comment by jancarloviray** [comment]
This project is quite awesome! +1 production +1 flux :)
