### ISSUE TITLE
react-a11y error on building production bundle

### ISSUE THREAD

**Issue by luandro** [irvinebroque/isomorphic-hot-loader#23]
When I run `npm run build` I get this error:
```
ERROR in ./components/App.js
Module not found: Error: Cannot resolve module 'function () {}' in /Users/me/project/components
 @ ./components/App.js 9:11-32
```

Commenting react-a11y out from App.js fixes the problem. But I just want to let you know.

**Comment by irvinebroque** [comment]
Thanks for the heads up! I'll take a look at this tonight.

**Comment by MickCoelho** [comment]
Sounds like it's coming from the `react-a11y` alias for the production 

```
config.resolve.alias = {'react-a11y': function() {}}; // Aliases react-a11y to nothing in production
```

**Comment by debradley** [comment]
Still a problem on clean checkout I made on 7/22, looks like MickCoelho is correct about the issue.

**Comment by Andersos** [comment]
Also HMR and WDS seems to be running when running the production script. That cant be correct. Hot module replacement should not be enabled when running in production.
![skjermbilde 2015-09-18 kl 12 57 18](https://cloud.githubusercontent.com/assets/288977/9957937/e6d3e07a-5e04-11e5-92fe-8db2366cc83e.png)
